correct Makefile

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -44,3 +44,8 @@ jobs:
         run: |
           chmod +x test.sh
           ./test.sh
+          if [[ $? -ne 0 ]];
+          then
+            echo "PROGRAM FAILED ON TEST CASES"
+            exit 1
+          fi
