correct Makefile (#7)
* correct Makefile

* fix testing.yml

* fix testing.yml

* fix testing.yml

* fix testing.yml

* Update testing.yml

* Update testing.yml

* Update testing.yml

* update test.sh

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -36,11 +36,16 @@ jobs:
       - name: install required packages
         run: |
           python -m pip install --upgrade pip
-          pip install ply
-        
+          pip3 install ply
 
       # Runs a set of commands using the runners shell
       - name: Running test on lexer
         run: |
           chmod +x test.sh
+          chmod +x bin/lexer
           ./test.sh
+          if [[ $? -ne 0 ]];
+          then
+            echo "PROGRAM FAILED ON TEST CASES"
+            exit 1
+          fi
